ah_dc            = "ams1"
ah_token         = "your_token_from_hoster"
ah_machine_type  = "start-xs"
ah_image_type    = "centos-7-x64"
ah_hdd           = "ssd2-ams1"
ah_fp            = "your_hash_key"
private_key_path = "/root/.ssh/id_rsa.pub"
